-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 17:26:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NewHospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NewHospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NewHospital` DEFAULT CHARACTER SET utf8 ;
USE `NewHospital` ;

-- -----------------------------------------------------
-- Table `NewHospital`.`Enfermeira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewHospital`.`Enfermeira` (
  `cpfEnfermeira` VARCHAR(10) NOT NULL,
  `senhaAcessoEnf` VARCHAR(30) NOT NULL,
  `nomeEnfermeira` VARCHAR(50) NOT NULL,
  `telefoneEnfermeira` VARCHAR(30) NULL,
  PRIMARY KEY (`cpfEnfermeira`),
  UNIQUE INDEX `idEnfermeira_UNIQUE` (`cpfEnfermeira` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NewHospital`.`Caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewHospital`.`Caixa` (
  `idCaixa` INT NOT NULL AUTO_INCREMENT,
  `descricaoCaixa` VARCHAR(100) NOT NULL,
  `Empresa` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCaixa`),
  UNIQUE INDEX `idCaixa_UNIQUE` (`idCaixa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NewHospital`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewHospital`.`Medico` (
  `cpfMedico` VARCHAR(10) NOT NULL,
  `senhaAcessoMed` VARCHAR(30) NOT NULL,
  `nomeMed` VARCHAR(50) NOT NULL,
  `telefoneMed` VARCHAR(30) NULL,
  PRIMARY KEY (`cpfMedico`),
  UNIQUE INDEX `idMedico_UNIQUE` (`cpfMedico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NewHospital`.`Cirurgia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewHospital`.`Cirurgia` (
  `idCirurgia` INT NOT NULL AUTO_INCREMENT,
  `nomePaciente` VARCHAR(50) NOT NULL,
  `dataCir` DATE NOT NULL,
  `obsCir` VARCHAR(100) NULL,
  `Medico_cpfMedico` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idCirurgia`, `Medico_cpfMedico`),
  UNIQUE INDEX `idCirurgia_UNIQUE` (`idCirurgia` ASC) VISIBLE,
  INDEX `fk_Cirurgia_Medico1_idx` (`Medico_cpfMedico` ASC) VISIBLE,
  CONSTRAINT `fk_Cirurgia_Medico1`
    FOREIGN KEY (`Medico_cpfMedico`)
    REFERENCES `NewHospital`.`Medico` (`cpfMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NewHospital`.`Bandeja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewHospital`.`Bandeja` (
  `idBandeja` INT NOT NULL AUTO_INCREMENT,
  `Cirurgia_idCirurgia` INT NOT NULL,
  `Caixa_idCaixa` INT NOT NULL,
  PRIMARY KEY (`idBandeja`, `Cirurgia_idCirurgia`, `Caixa_idCaixa`),
  UNIQUE INDEX `idBandeja_UNIQUE` (`idBandeja` ASC) VISIBLE,
  INDEX `fk_Bandeja_Cirurgia1_idx` (`Cirurgia_idCirurgia` ASC) VISIBLE,
  INDEX `fk_Bandeja_Caixa1_idx` (`Caixa_idCaixa` ASC) VISIBLE,
  CONSTRAINT `fk_Bandeja_Cirurgia1`
    FOREIGN KEY (`Cirurgia_idCirurgia`)
    REFERENCES `NewHospital`.`Cirurgia` (`idCirurgia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bandeja_Caixa1`
    FOREIGN KEY (`Caixa_idCaixa`)
    REFERENCES `NewHospital`.`Caixa` (`idCaixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NewHospital`.`Esterilizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewHospital`.`Esterilizacao` (
  `Enfermeira_cpfEnfermeira` VARCHAR(10) NOT NULL,
  `Bandeja_idBandeja` INT NOT NULL,
  `dataTime` DATETIME NOT NULL,
  `tipoEsterilizacao` VARCHAR(20) NOT NULL,
  `obsEsterilizacao` VARCHAR(100) NULL,
  PRIMARY KEY (`Enfermeira_cpfEnfermeira`, `Bandeja_idBandeja`),
  INDEX `fk_Esterilizacao_Bandeja1_idx` (`Bandeja_idBandeja` ASC) VISIBLE,
  INDEX `fk_Esterilizacao_Enfermeira1_idx` (`Enfermeira_cpfEnfermeira` ASC) VISIBLE,
  CONSTRAINT `fk_Esterilizacao_Bandeja1`
    FOREIGN KEY (`Bandeja_idBandeja`)
    REFERENCES `NewHospital`.`Bandeja` (`idBandeja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Esterilizacao_Enfermeira1`
    FOREIGN KEY (`Enfermeira_cpfEnfermeira`)
    REFERENCES `NewHospital`.`Enfermeira` (`cpfEnfermeira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NewHospital`.`Recebe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewHospital`.`Recebe` (
  `Caixa_idCaixa` INT NOT NULL,
  `Enfermeira_cpfEnfermeira` VARCHAR(10) NOT NULL,
  `dataTime` DATETIME NOT NULL,
  PRIMARY KEY (`Caixa_idCaixa`, `Enfermeira_cpfEnfermeira`),
  INDEX `fk_Enfermeira_has_Caixa_Caixa1_idx` (`Caixa_idCaixa` ASC) VISIBLE,
  INDEX `fk_Recebe_Enfermeira1_idx` (`Enfermeira_cpfEnfermeira` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermeira_has_Caixa_Caixa1`
    FOREIGN KEY (`Caixa_idCaixa`)
    REFERENCES `NewHospital`.`Caixa` (`idCaixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recebe_Enfermeira1`
    FOREIGN KEY (`Enfermeira_cpfEnfermeira`)
    REFERENCES `NewHospital`.`Enfermeira` (`cpfEnfermeira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
