/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.newhospital.views;

/**
 *
 * @author Leandro Pereira
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogiin
     */
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtf_cpf = new javax.swing.JTextField();
        jtf_senha = new javax.swing.JTextField();
        jl_entrar = new javax.swing.JLabel();
        jl_cadastro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_cpf.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel1.add(jtf_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 290, 30));

        jtf_senha.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel1.add(jtf_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 290, 30));

        jl_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/newhospital/images/Entrar.png"))); // NOI18N
        jl_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_entrarMouseClicked(evt);
            }
        });
        jPanel1.add(jl_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 130, -1));

        jl_cadastro.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jl_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        jl_cadastro.setText("CRIAR NOVO ACESSO");
        jl_cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_cadastroMouseClicked(evt);
            }
        });
        jPanel1.add(jl_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/newhospital/images/Login.jpg"))); // NOI18N
        jPanel1.add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_cadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_cadastroMouseClicked
        // TODO add your handling code here:
        TelaCadastro screenCad = new TelaCadastro();

        screenCad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jl_cadastroMouseClicked

    private void jl_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_entrarMouseClicked
        // TODO add your handling code here:
        TelaMenu screenMenu = new TelaMenu();

        screenMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jl_entrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_cadastro;
    private javax.swing.JLabel jl_entrar;
    private javax.swing.JTextField jtf_cpf;
    private javax.swing.JTextField jtf_senha;
    // End of variables declaration//GEN-END:variables
}
